baseURL = "https://alisakobzar.github.io/"
languageCode = "en-us"
title = "Alisa Kobzar"
theme = "digitalgarden"

[Params]
  description = "Alisa Kobzar's portfolio webpage"
  images = ['favicon.ico']
  enableSearch = true

[menu]
[[menu.main]]
  name = 'info'
  url = '/'
  weight = 1


[[menu.social]]
  name = 'Email'
  url = 'mailto:alisa@mur.at'
  weight = 1


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
