baseURL = "https://alisakobzar.github.io/"
languageCode = "en-us"
title = "Alisa Kobzar"
theme = "digitalgarden"

[Params]
  description = "Alisa Kobzar Portfolio"
  images = ['/favicon.ico']
  enableSearch = true

[menu]
[[menu.main]]
  name = 'Agenda'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'Compositions'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Acoustic'
  url = '/acoustic'
  weight = 3
[[menu.main]]
  name = 'Electro-acoustic'
  url = '/electro-acoustic'
  weight = 4
[[menu.main]]
  name = 'Electronic'
  url = '/electronic'
  weight = 5

[[menu.main]]
  name = 'Art-projects'
  params.header = true
  weight = 7
[[menu.main]]
  name = 'Duo-rotkaeppchen'
  url = '/duo-rotkaeppchen'
  weight = 8
[[menu.main]]
  name = 'Duo-with-A.-Vorobiova'
  url = '/duo-nastia'
  weight = 9
[[menu.main]]
  name = 'Installations'
  url = '/installations'
  weight = 10
[[menu.main]]
  name = 'Collaborations'
  url = '/collaborations'
  weight = 11


[[menu.main]]
  name = 'Activities'
  params.header = true
  weight = 12
[[menu.main]]
  name = 'Video-design, filming'
  url = '/video'
  weight = 13
[[menu.main]]
  name = 'HCI, GameDev, NotGameDev'
  url = '/gamedev'
  weight = 14
[[menu.main]]
  name = 'Sound-directing'
  url = '/sounddir'
  weight = 15
[[menu.main]]
  name = 'Texts'
  url = '/writings'
  weight = 16

[[menu.main]]
  name = 'About me'
  params.header = true
  weight = 18
[[menu.main]]
  name = 'CV'
  url = '/cv-en'
  weight = 19
[[menu.main]]
  name = 'Photos'
  url = '/photos'
  weight = 20




[[menu.social]]
  name = 'Email'
  url = 'mailto:alisa.kherson1989@gmail.com'
  weight = 1


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
